apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-sweep-bot-secret
  namespace: discord-sweep-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: discord-sweep-bot-secret
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: cc8b93f8-0d38-4a2c-93e1-b43f011f8c6b
